/**
 * Shutterstock API Reference
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/InlineResponse20031Header', '../model/InlineResponse20031Query'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20031Header'), require('./InlineResponse20031Query'));
  } else {
    // Browser globals (root is window)
    if (!root.ShutterstockApiReference) {
      root.ShutterstockApiReference = {};
    }
    root.ShutterstockApiReference.InlineResponse20031 = factory(root.ShutterstockApiReference.ApiClient, root.ShutterstockApiReference.InlineResponse20031Header, root.ShutterstockApiReference.InlineResponse20031Query);
  }
}(this, function(ApiClient, InlineResponse20031Header, InlineResponse20031Query) {
  'use strict';




  /**
   * The InlineResponse20031 model module.
   * @module model/InlineResponse20031
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>InlineResponse20031</code>.
   * Validation results
   * @alias module:model/InlineResponse20031
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse20031</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20031} obj Optional instance to populate.
   * @return {module:model/InlineResponse20031} The populated <code>InlineResponse20031</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('header')) {
        obj['header'] = InlineResponse20031Header.constructFromObject(data['header']);
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = InlineResponse20031Query.constructFromObject(data['query']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse20031Header} header
   */
  exports.prototype['header'] = undefined;
  /**
   * @member {module:model/InlineResponse20031Query} query
   */
  exports.prototype['query'] = undefined;



  return exports;
}));


