/**
 * Shutterstock API Reference
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/InlineResponse20025Data'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20025Data'));
  } else {
    // Browser globals (root is window)
    if (!root.ShutterstockApiReference) {
      root.ShutterstockApiReference = {};
    }
    root.ShutterstockApiReference.InlineResponse20025 = factory(root.ShutterstockApiReference.ApiClient, root.ShutterstockApiReference.InlineResponse20025Data);
  }
}(this, function(ApiClient, InlineResponse20025Data) {
  'use strict';




  /**
   * The InlineResponse20025 model module.
   * @module model/InlineResponse20025
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>InlineResponse20025</code>.
   * List of catalog collection items
   * @alias module:model/InlineResponse20025
   * @class
   * @param page {Number} 
   * @param per_page {Number} 
   * @param total_count {Number} 
   * @param data {Array.<module:model/InlineResponse20025Data>} List of catalog collection items
   */
  var exports = function(page, per_page, total_count, data) {
    var _this = this;

    _this['page'] = page;
    _this['per_page'] = per_page;
    _this['total_count'] = total_count;
    _this['data'] = data;
  };

  /**
   * Constructs a <code>InlineResponse20025</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20025} obj Optional instance to populate.
   * @return {module:model/InlineResponse20025} The populated <code>InlineResponse20025</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('page')) {
        obj['page'] = ApiClient.convertToType(data['page'], 'Number');
      }
      if (data.hasOwnProperty('per_page')) {
        obj['per_page'] = ApiClient.convertToType(data['per_page'], 'Number');
      }
      if (data.hasOwnProperty('total_count')) {
        obj['total_count'] = ApiClient.convertToType(data['total_count'], 'Number');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [InlineResponse20025Data]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} page
   */
  exports.prototype['page'] = undefined;
  /**
   * @member {Number} per_page
   */
  exports.prototype['per_page'] = undefined;
  /**
   * @member {Number} total_count
   */
  exports.prototype['total_count'] = undefined;
  /**
   * List of catalog collection items
   * @member {Array.<module:model/InlineResponse20025Data>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


