/**
 * Shutterstock API Reference
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * OpenAPI spec version: 1.5.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ShutterstockApiReference) {
      root.ShutterstockApiReference = {};
    }
    root.ShutterstockApiReference.InlineResponse200Errors = factory(root.ShutterstockApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse200Errors model module.
   * @module model/InlineResponse200Errors
   * @version 1.5.2
   */

  /**
   * Constructs a new <code>InlineResponse200Errors</code>.
   * Error object
   * @alias module:model/InlineResponse200Errors
   * @class
   * @param message {String} Specific details about this error
   */
  var exports = function(message) {
    var _this = this;





    _this['message'] = message;

  };

  /**
   * Constructs a <code>InlineResponse200Errors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200Errors} obj Optional instance to populate.
   * @return {module:model/InlineResponse200Errors} The populated <code>InlineResponse200Errors</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('statusCode')) {
        obj['statusCode'] = ApiClient.convertToType(data['statusCode'], 'Number');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'String');
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [Object]);
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
    }
    return obj;
  }

  /**
   * HTTP Error code
   * @member {Number} statusCode
   */
  exports.prototype['statusCode'] = undefined;
  /**
   * The error code of this error
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * Debugging information about the error
   * @member {String} data
   */
  exports.prototype['data'] = undefined;
  /**
   * A list of items that produced the error
   * @member {Array.<Object>} items
   */
  exports.prototype['items'] = undefined;
  /**
   * Specific details about this error
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * Internal code reference to the source of the error
   * @member {String} path
   */
  exports.prototype['path'] = undefined;



  return exports;
}));


