/**
 * Shutterstock API Reference
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * OpenAPI spec version: 1.1.42
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.9
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ShutterstockApiReference) {
      root.ShutterstockApiReference = {};
    }
    root.ShutterstockApiReference.InlineResponse2007AssetsThumbJpgs = factory(root.ShutterstockApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2007AssetsThumbJpgs model module.
   * @module model/InlineResponse2007AssetsThumbJpgs
   * @version 1.1.42
   */

  /**
   * Constructs a new <code>InlineResponse2007AssetsThumbJpgs</code>.
   * List of URLs
   * @alias module:model/InlineResponse2007AssetsThumbJpgs
   * @class
   * @param urls {Array.<String>} URLs
   */
  var exports = function(urls) {
    var _this = this;

    _this['urls'] = urls;
  };

  /**
   * Constructs a <code>InlineResponse2007AssetsThumbJpgs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007AssetsThumbJpgs} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007AssetsThumbJpgs} The populated <code>InlineResponse2007AssetsThumbJpgs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('urls')) {
        obj['urls'] = ApiClient.convertToType(data['urls'], ['String']);
      }
    }
    return obj;
  }

  /**
   * URLs
   * @member {Array.<String>} urls
   */
  exports.prototype['urls'] = undefined;



  return exports;
}));


