/**
 * Shutterstock API Reference
 * The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.
 *
 * OpenAPI spec version: 1.0.31
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ShutterstockApiReference) {
      root.ShutterstockApiReference = {};
    }
    root.ShutterstockApiReference.OauthAccessTokenResponse = factory(root.ShutterstockApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OauthAccessTokenResponse model module.
   * @module model/OauthAccessTokenResponse
   * @version 1.0.31
   */

  /**
   * Constructs a new <code>OauthAccessTokenResponse</code>.
   * Access token response to client apps
   * @alias module:model/OauthAccessTokenResponse
   * @class
   * @param access_token {String} Access token that can be used for future requests
   * @param token_type {String} Type of token
   */
  var exports = function(access_token, token_type) {
    var _this = this;

    _this['access_token'] = access_token;

    _this['token_type'] = token_type;


  };

  /**
   * Constructs a <code>OauthAccessTokenResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OauthAccessTokenResponse} obj Optional instance to populate.
   * @return {module:model/OauthAccessTokenResponse} The populated <code>OauthAccessTokenResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('access_token')) {
        obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
      }
      if (data.hasOwnProperty('expires_in')) {
        obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
      }
      if (data.hasOwnProperty('token_type')) {
        obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
      }
      if (data.hasOwnProperty('refresh_token')) {
        obj['refresh_token'] = ApiClient.convertToType(data['refresh_token'], 'String');
      }
      if (data.hasOwnProperty('user_token')) {
        obj['user_token'] = ApiClient.convertToType(data['user_token'], 'String');
      }
    }
    return obj;
  }

  /**
   * Access token that can be used for future requests
   * @member {String} access_token
   */
  exports.prototype['access_token'] = undefined;
  /**
   * Number of seconds before token expires, only present for expiring tokens
   * @member {Number} expires_in
   */
  exports.prototype['expires_in'] = undefined;
  /**
   * Type of token
   * @member {String} token_type
   * @default 'Bearer'
   */
  exports.prototype['token_type'] = 'Bearer';
  /**
   * A refresh token that can be used to renew the access_token when it expires, only present for expiring tokens
   * @member {String} refresh_token
   */
  exports.prototype['refresh_token'] = undefined;
  /**
   * Metadata about the access_token, only present for expiring tokens
   * @member {String} user_token
   */
  exports.prototype['user_token'] = undefined;



  return exports;
}));


